name = "justinsengineering"
compatibility_date = "2026-02-20"
send_metrics = false
workers_dev = false

[assets]
directory = "./target/dx/justinsengineering/release/web/public"
not_found_handling = "single-page-application"
